[2024-05-13T14:47:41.799+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-13T14:47:41.827+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: students.load manual__2024-05-13T14:47:33.855952+00:00 [queued]>
[2024-05-13T14:47:41.837+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: students.load manual__2024-05-13T14:47:33.855952+00:00 [queued]>
[2024-05-13T14:47:41.838+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-13T14:47:41.859+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load> on 2024-05-13 14:47:33.855952+00:00
[2024-05-13T14:47:41.868+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1501) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-13T14:47:41.870+0000] {standard_task_runner.py:63} INFO - Started process 1503 to run task
[2024-05-13T14:47:41.870+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'students', 'load', 'manual__2024-05-13T14:47:33.855952+00:00', '--job-id', '261', '--raw', '--subdir', 'DAGS_FOLDER/students.py', '--cfg-path', '/tmp/tmpi1_1a_lz']
[2024-05-13T14:47:41.874+0000] {standard_task_runner.py:91} INFO - Job 261: Subtask load
[2024-05-13T14:47:41.937+0000] {task_command.py:426} INFO - Running <TaskInstance: students.load manual__2024-05-13T14:47:33.855952+00:00 [running]> on host c2025ffc2c56
[2024-05-13T14:47:42.086+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='students' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-05-13T14:47:33.855952+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-13T14:47:33.855952+00:00'
[2024-05-13T14:47:42.089+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-13T14:47:42.090+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-13T14:47:42.091+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/students.py", line 38, in load
    with open(target_file, 'a') as f:
              ^^^^^^^^^^^
NameError: name 'target_file' is not defined
[2024-05-13T14:47:42.115+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=students, task_id=load, run_id=manual__2024-05-13T14:47:33.855952+00:00, execution_date=20240513T144733, start_date=20240513T144741, end_date=20240513T144742
[2024-05-13T14:47:42.133+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 261 for task load (name 'target_file' is not defined; 1503)
[2024-05-13T14:47:42.166+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-13T14:47:42.189+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-13T14:47:42.193+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
