[2024-05-19T15:22:53.181+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-19T15:22:53.211+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dummyjson.write_to_csv_todo scheduled__2024-05-17T17:00:00+00:00 [queued]>
[2024-05-19T15:22:53.227+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dummyjson.write_to_csv_todo scheduled__2024-05-17T17:00:00+00:00 [queued]>
[2024-05-19T15:22:53.228+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 6
[2024-05-19T15:22:53.254+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): write_to_csv_todo> on 2024-05-17 17:00:00+00:00
[2024-05-19T15:22:53.264+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1675) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-19T15:22:53.267+0000] {standard_task_runner.py:63} INFO - Started process 1680 to run task
[2024-05-19T15:22:53.267+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dummyjson', 'write_to_csv_todo', 'scheduled__2024-05-17T17:00:00+00:00', '--job-id', '2002', '--raw', '--subdir', 'DAGS_FOLDER/dummyjson.py', '--cfg-path', '/tmp/tmp16_3fygl']
[2024-05-19T15:22:53.272+0000] {standard_task_runner.py:91} INFO - Job 2002: Subtask write_to_csv_todo
[2024-05-19T15:22:53.370+0000] {task_command.py:426} INFO - Running <TaskInstance: dummyjson.write_to_csv_todo scheduled__2024-05-17T17:00:00+00:00 [running]> on host ca927d78a9ea
[2024-05-19T15:22:53.995+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='fathurrahmanhernanda@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dummyjson' AIRFLOW_CTX_TASK_ID='write_to_csv_todo' AIRFLOW_CTX_EXECUTION_DATE='2024-05-17T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-17T17:00:00+00:00'
[2024-05-19T15:22:53.997+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-19T15:22:54.034+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-19T15:22:54.035+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dummyjson.py", line 107, in write_to_csv_generic
    writer.writerows(transformed_data)
  File "/usr/local/lib/python3.12/csv.py", line 167, in writerows
    return self.writer.writerows(map(self._dict_to_list, rowdicts))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/csv.py", line 159, in _dict_to_list
    raise ValueError("dict contains fields not in fieldnames: "
ValueError: dict contains fields not in fieldnames: 'user_id', 'todo_id'
[2024-05-19T15:22:54.060+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dummyjson, task_id=write_to_csv_todo, run_id=scheduled__2024-05-17T17:00:00+00:00, execution_date=20240517T170000, start_date=20240519T152253, end_date=20240519T152254
[2024-05-19T15:22:54.094+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2002 for task write_to_csv_todo (dict contains fields not in fieldnames: 'user_id', 'todo_id'; 1680)
[2024-05-19T15:22:54.139+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-19T15:22:54.160+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
