[2024-05-16T12:18:09.492+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-16T12:18:09.520+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: randomuser_ingestion.check_user_age manual__2024-05-16T12:18:04.792682+00:00 [queued]>
[2024-05-16T12:18:09.532+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: randomuser_ingestion.check_user_age manual__2024-05-16T12:18:04.792682+00:00 [queued]>
[2024-05-16T12:18:09.533+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-16T12:18:09.559+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): check_user_age> on 2024-05-16 12:18:04.792682+00:00
[2024-05-16T12:18:09.573+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2463) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-16T12:18:09.575+0000] {standard_task_runner.py:63} INFO - Started process 2468 to run task
[2024-05-16T12:18:09.577+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'randomuser_ingestion', 'check_user_age', 'manual__2024-05-16T12:18:04.792682+00:00', '--job-id', '1087', '--raw', '--subdir', 'DAGS_FOLDER/randomuser_ingestion.py', '--cfg-path', '/tmp/tmpdda3nrjb']
[2024-05-16T12:18:09.582+0000] {standard_task_runner.py:91} INFO - Job 1087: Subtask check_user_age
[2024-05-16T12:18:09.663+0000] {task_command.py:426} INFO - Running <TaskInstance: randomuser_ingestion.check_user_age manual__2024-05-16T12:18:04.792682+00:00 [running]> on host 8d1d9b6df744
[2024-05-16T12:18:09.889+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='randomuser_ingestion' AIRFLOW_CTX_TASK_ID='check_user_age' AIRFLOW_CTX_EXECUTION_DATE='2024-05-16T12:18:04.792682+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-16T12:18:04.792682+00:00'
[2024-05-16T12:18:09.897+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-16T12:18:09.905+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-05-16T12:18:09.927+0000] {logging_mixin.py:188} INFO - None <class 'NoneType'>
[2024-05-16T12:18:09.928+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-16T12:18:09.929+0000] {branch.py:36} INFO - Branch into None
[2024-05-16T12:18:09.930+0000] {skipmixin.py:178} INFO - Following branch None
[2024-05-16T12:18:09.931+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-16T12:18:09.947+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=randomuser_ingestion, task_id=check_user_age, run_id=manual__2024-05-16T12:18:04.792682+00:00, execution_date=20240516T121804, start_date=20240516T121809, end_date=20240516T121809
[2024-05-16T12:18:09.992+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-16T12:18:10.035+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-16T12:18:10.039+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
