[2024-05-19T12:59:36.907+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-19T12:59:36.942+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_products_from_api.load_to_bigquery manual__2024-05-19T12:54:16.872279+00:00 [queued]>
[2024-05-19T12:59:36.956+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_products_from_api.load_to_bigquery manual__2024-05-19T12:54:16.872279+00:00 [queued]>
[2024-05-19T12:59:36.958+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 4
[2024-05-19T12:59:36.989+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_to_bigquery> on 2024-05-19 12:54:16.872279+00:00
[2024-05-19T12:59:37.001+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=4922) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-19T12:59:37.004+0000] {standard_task_runner.py:63} INFO - Started process 4924 to run task
[2024-05-19T12:59:37.005+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'extract_products_from_api', 'load_to_bigquery', 'manual__2024-05-19T12:54:16.872279+00:00', '--job-id', '1829', '--raw', '--subdir', 'DAGS_FOLDER/dummyjson_product.py', '--cfg-path', '/tmp/tmpfjkoq59y']
[2024-05-19T12:59:37.007+0000] {standard_task_runner.py:91} INFO - Job 1829: Subtask load_to_bigquery
[2024-05-19T12:59:37.083+0000] {task_command.py:426} INFO - Running <TaskInstance: extract_products_from_api.load_to_bigquery manual__2024-05-19T12:54:16.872279+00:00 [running]> on host ca927d78a9ea
[2024-05-19T12:59:37.572+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your_email@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_products_from_api' AIRFLOW_CTX_TASK_ID='load_to_bigquery' AIRFLOW_CTX_EXECUTION_DATE='2024-05-19T12:54:16.872279+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-19T12:54:16.872279+00:00'
[2024-05-19T12:59:37.573+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-19T12:59:37.575+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-19T12:59:37.576+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: load_to_bigquery() missing 1 required positional argument: 'context'
[2024-05-19T12:59:37.593+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=extract_products_from_api, task_id=load_to_bigquery, run_id=manual__2024-05-19T12:54:16.872279+00:00, execution_date=20240519T125416, start_date=20240519T125936, end_date=20240519T125937
[2024-05-19T12:59:37.619+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1829 for task load_to_bigquery (load_to_bigquery() missing 1 required positional argument: 'context'; 4924)
[2024-05-19T12:59:37.661+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-19T12:59:37.701+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-19T12:59:37.705+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
