[2024-05-19T12:22:33.358+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: dummyjson_products.local_to_gcs_products manual__2024-05-19T12:17:10.391759+00:00 [queued]> finished (success) although the task says it's queued. (Info: None) Was the task killed externally?
