[2024-05-16T12:20:55.964+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-16T12:20:55.994+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: randomuser_ingestion.check_user_age manual__2024-05-16T12:20:52.814529+00:00 [queued]>
[2024-05-16T12:20:56.009+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: randomuser_ingestion.check_user_age manual__2024-05-16T12:20:52.814529+00:00 [queued]>
[2024-05-16T12:20:56.011+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-16T12:20:56.039+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): check_user_age> on 2024-05-16 12:20:52.814529+00:00
[2024-05-16T12:20:56.062+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2510) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-16T12:20:56.065+0000] {standard_task_runner.py:63} INFO - Started process 2515 to run task
[2024-05-16T12:20:56.065+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'randomuser_ingestion', 'check_user_age', 'manual__2024-05-16T12:20:52.814529+00:00', '--job-id', '1090', '--raw', '--subdir', 'DAGS_FOLDER/randomuser_ingestion.py', '--cfg-path', '/tmp/tmp01dlzsbr']
[2024-05-16T12:20:56.069+0000] {standard_task_runner.py:91} INFO - Job 1090: Subtask check_user_age
[2024-05-16T12:20:56.146+0000] {task_command.py:426} INFO - Running <TaskInstance: randomuser_ingestion.check_user_age manual__2024-05-16T12:20:52.814529+00:00 [running]> on host 8d1d9b6df744
[2024-05-16T12:20:56.293+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='randomuser_ingestion' AIRFLOW_CTX_TASK_ID='check_user_age' AIRFLOW_CTX_EXECUTION_DATE='2024-05-16T12:20:52.814529+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-16T12:20:52.814529+00:00'
[2024-05-16T12:20:56.296+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-16T12:20:56.296+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-05-16T12:20:56.311+0000] {logging_mixin.py:188} INFO - None <class 'NoneType'>
[2024-05-16T12:20:56.312+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-16T12:20:56.313+0000] {branch.py:36} INFO - Branch into None
[2024-05-16T12:20:56.314+0000] {skipmixin.py:178} INFO - Following branch None
[2024-05-16T12:20:56.315+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-16T12:20:56.330+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=randomuser_ingestion, task_id=check_user_age, run_id=manual__2024-05-16T12:20:52.814529+00:00, execution_date=20240516T122052, start_date=20240516T122055, end_date=20240516T122056
[2024-05-16T12:20:56.362+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-16T12:20:56.391+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-16T12:20:56.394+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
