[2024-05-19T15:18:10.230+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-19T15:18:10.262+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dummyjson.write_to_csv_post manual__2024-05-19T15:17:18.366686+00:00 [queued]>
[2024-05-19T15:18:10.282+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dummyjson.write_to_csv_post manual__2024-05-19T15:17:18.366686+00:00 [queued]>
[2024-05-19T15:18:10.283+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-05-19T15:18:10.310+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): write_to_csv_post> on 2024-05-19 15:17:18.366686+00:00
[2024-05-19T15:18:10.323+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1533) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-19T15:18:10.326+0000] {standard_task_runner.py:63} INFO - Started process 1538 to run task
[2024-05-19T15:18:10.327+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dummyjson', 'write_to_csv_post', 'manual__2024-05-19T15:17:18.366686+00:00', '--job-id', '1974', '--raw', '--subdir', 'DAGS_FOLDER/dummyjson.py', '--cfg-path', '/tmp/tmpkppmv39b']
[2024-05-19T15:18:10.329+0000] {standard_task_runner.py:91} INFO - Job 1974: Subtask write_to_csv_post
[2024-05-19T15:18:10.412+0000] {task_command.py:426} INFO - Running <TaskInstance: dummyjson.write_to_csv_post manual__2024-05-19T15:17:18.366686+00:00 [running]> on host ca927d78a9ea
[2024-05-19T15:18:10.873+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='fathurrahmanhernanda@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dummyjson' AIRFLOW_CTX_TASK_ID='write_to_csv_post' AIRFLOW_CTX_EXECUTION_DATE='2024-05-19T15:17:18.366686+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-19T15:17:18.366686+00:00'
[2024-05-19T15:18:10.875+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-19T15:18:10.898+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-19T15:18:10.899+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dummyjson.py", line 107, in write_to_csv_generic
    writer.writerows(transformed_data)
  File "/usr/local/lib/python3.12/csv.py", line 167, in writerows
    return self.writer.writerows(map(self._dict_to_list, rowdicts))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/csv.py", line 159, in _dict_to_list
    raise ValueError("dict contains fields not in fieldnames: "
ValueError: dict contains fields not in fieldnames: 'post_id', 'user_id'
[2024-05-19T15:18:10.923+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dummyjson, task_id=write_to_csv_post, run_id=manual__2024-05-19T15:17:18.366686+00:00, execution_date=20240519T151718, start_date=20240519T151810, end_date=20240519T151810
[2024-05-19T15:18:10.947+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1974 for task write_to_csv_post (dict contains fields not in fieldnames: 'post_id', 'user_id'; 1538)
[2024-05-19T15:18:10.985+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-19T15:18:11.049+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-19T15:18:11.052+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
