[2024-05-18T16:03:00.249+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-18T16:03:00.273+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dummyjson_ingestion.transform_user manual__2024-05-18T16:01:32.590746+00:00 [queued]>
[2024-05-18T16:03:00.285+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dummyjson_ingestion.transform_user manual__2024-05-18T16:01:32.590746+00:00 [queued]>
[2024-05-18T16:03:00.287+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 7
[2024-05-18T16:03:00.335+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_user> on 2024-05-18 16:01:32.590746+00:00
[2024-05-18T16:03:00.343+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1386) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-18T16:03:00.345+0000] {standard_task_runner.py:63} INFO - Started process 1388 to run task
[2024-05-18T16:03:00.345+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dummyjson_ingestion', 'transform_user', 'manual__2024-05-18T16:01:32.590746+00:00', '--job-id', '1194', '--raw', '--subdir', 'DAGS_FOLDER/dummyjson_ingestion.py', '--cfg-path', '/tmp/tmp3aheso6m']
[2024-05-18T16:03:00.348+0000] {standard_task_runner.py:91} INFO - Job 1194: Subtask transform_user
[2024-05-18T16:03:00.447+0000] {task_command.py:426} INFO - Running <TaskInstance: dummyjson_ingestion.transform_user manual__2024-05-18T16:01:32.590746+00:00 [running]> on host 8d1d9b6df744
[2024-05-18T16:03:00.663+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='fathurrahmanhernanda@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dummyjson_ingestion' AIRFLOW_CTX_TASK_ID='transform_user' AIRFLOW_CTX_EXECUTION_DATE='2024-05-18T16:01:32.590746+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-18T16:01:32.590746+00:00'
[2024-05-18T16:03:00.666+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-18T16:03:00.689+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-18T16:03:00.690+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dummyjson_ingestion.py", line 38, in transform_user
    print(response, type(user))
                         ^^^^
NameError: name 'user' is not defined
[2024-05-18T16:03:00.713+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dummyjson_ingestion, task_id=transform_user, run_id=manual__2024-05-18T16:01:32.590746+00:00, execution_date=20240518T160132, start_date=20240518T160300, end_date=20240518T160300
[2024-05-18T16:03:00.765+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1194 for task transform_user (name 'user' is not defined; 1388)
[2024-05-18T16:03:00.802+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-18T16:03:00.824+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-18T16:03:00.848+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
