[2024-05-19T11:46:35.685+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: dummyjson_products.write_to_csv_products manual__2024-05-19T11:30:27.191769+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
