[2024-05-19T12:17:14.523+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: dummyjson_products.extract_products manual__2024-05-19T12:17:10.391759+00:00 [queued]> finished (success) although the task says it's queued. (Info: None) Was the task killed externally?
