[2024-05-19T09:09:31.060+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-19T09:09:31.089+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dummyjson_ingestion.write_to_csv manual__2024-05-19T09:09:12.636391+00:00 [queued]>
[2024-05-19T09:09:31.101+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dummyjson_ingestion.write_to_csv manual__2024-05-19T09:09:12.636391+00:00 [queued]>
[2024-05-19T09:09:31.104+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-05-19T09:09:31.125+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): write_to_csv> on 2024-05-19 09:09:12.636391+00:00
[2024-05-19T09:09:31.135+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=645) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-19T09:09:31.137+0000] {standard_task_runner.py:63} INFO - Started process 647 to run task
[2024-05-19T09:09:31.138+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dummyjson_ingestion', 'write_to_csv', 'manual__2024-05-19T09:09:12.636391+00:00', '--job-id', '1338', '--raw', '--subdir', 'DAGS_FOLDER/dummyjson_ingestion.py', '--cfg-path', '/tmp/tmpkyvqi6o8']
[2024-05-19T09:09:31.140+0000] {standard_task_runner.py:91} INFO - Job 1338: Subtask write_to_csv
[2024-05-19T09:09:31.202+0000] {task_command.py:426} INFO - Running <TaskInstance: dummyjson_ingestion.write_to_csv manual__2024-05-19T09:09:12.636391+00:00 [running]> on host ca927d78a9ea
[2024-05-19T09:09:31.582+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='fathurrahmanhernanda@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dummyjson_ingestion' AIRFLOW_CTX_TASK_ID='write_to_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-05-19T09:09:12.636391+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-19T09:09:12.636391+00:00'
[2024-05-19T09:09:31.583+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-19T09:09:31.605+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-19T09:09:31.605+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dummyjson_ingestion.py", line 58, in write_to_csv
    writer.writerow(user)
  File "/usr/local/lib/python3.12/csv.py", line 164, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/csv.py", line 159, in _dict_to_list
    raise ValueError("dict contains fields not in fieldnames: "
ValueError: dict contains fields not in fieldnames: 'user_id'
[2024-05-19T09:09:31.625+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dummyjson_ingestion, task_id=write_to_csv, run_id=manual__2024-05-19T09:09:12.636391+00:00, execution_date=20240519T090912, start_date=20240519T090931, end_date=20240519T090931
[2024-05-19T09:09:31.643+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1338 for task write_to_csv (dict contains fields not in fieldnames: 'user_id'; 647)
[2024-05-19T09:09:31.674+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-19T09:09:31.706+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-19T09:09:31.710+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
