[2024-05-19T12:08:59.219+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: dummyjson_products.write_to_csv_products manual__2024-05-19T12:08:41.939068+00:00 [queued]> finished (success) although the task says it's queued. (Info: None) Was the task killed externally?
