[2024-05-19T12:48:57.247+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-19T12:48:57.270+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_products_from_api.upload_to_gcs manual__2024-05-19T12:40:45.140200+00:00 [queued]>
[2024-05-19T12:48:57.287+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_products_from_api.upload_to_gcs manual__2024-05-19T12:40:45.140200+00:00 [queued]>
[2024-05-19T12:48:57.289+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-05-19T12:48:57.325+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): upload_to_gcs> on 2024-05-19 12:40:45.140200+00:00
[2024-05-19T12:48:57.339+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=4626) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-19T12:48:57.342+0000] {standard_task_runner.py:63} INFO - Started process 4635 to run task
[2024-05-19T12:48:57.343+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'extract_products_from_api', 'upload_to_gcs', 'manual__2024-05-19T12:40:45.140200+00:00', '--job-id', '1777', '--raw', '--subdir', 'DAGS_FOLDER/dummyjson_product.py', '--cfg-path', '/tmp/tmpmlgww6lq']
[2024-05-19T12:48:57.346+0000] {standard_task_runner.py:91} INFO - Job 1777: Subtask upload_to_gcs
[2024-05-19T12:48:57.433+0000] {task_command.py:426} INFO - Running <TaskInstance: extract_products_from_api.upload_to_gcs manual__2024-05-19T12:40:45.140200+00:00 [running]> on host ca927d78a9ea
[2024-05-19T12:48:57.563+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your_email@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_products_from_api' AIRFLOW_CTX_TASK_ID='upload_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2024-05-19T12:40:45.140200+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-19T12:40:45.140200+00:00'
[2024-05-19T12:48:57.565+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-19T12:48:57.567+0000] {baseoperator.py:399} WARNING - LocalFilesystemToGCSOperator.execute cannot be called outside TaskInstance!
[2024-05-19T12:48:57.582+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-19T12:48:57.599+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dummyjson_product.py", line 56, in upload_to_gcs
    return task.execute(context=None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/transfers/local_to_gcs.py", line 91, in execute
    hook = GCSHook(
           ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 160, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 252, in __init__
    self.extras: dict = self.get_connection(self.gcp_conn_id).extra_dejson
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `google_cloud_default` isn't defined
[2024-05-19T12:48:57.610+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=extract_products_from_api, task_id=upload_to_gcs, run_id=manual__2024-05-19T12:40:45.140200+00:00, execution_date=20240519T124045, start_date=20240519T124857, end_date=20240519T124857
[2024-05-19T12:48:57.884+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1777 for task upload_to_gcs (The conn_id `google_cloud_default` isn't defined; 4635)
[2024-05-19T12:48:57.921+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-19T12:48:57.956+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-19T12:48:57.959+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
