[2024-05-19T15:18:07.281+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-19T15:18:07.311+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dummyjson.write_to_csv_todo manual__2024-05-19T15:17:18.366686+00:00 [queued]>
[2024-05-19T15:18:07.331+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dummyjson.write_to_csv_todo manual__2024-05-19T15:17:18.366686+00:00 [queued]>
[2024-05-19T15:18:07.332+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-05-19T15:18:07.361+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): write_to_csv_todo> on 2024-05-19 15:17:18.366686+00:00
[2024-05-19T15:18:07.372+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1527) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-19T15:18:07.374+0000] {standard_task_runner.py:63} INFO - Started process 1536 to run task
[2024-05-19T15:18:07.375+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dummyjson', 'write_to_csv_todo', 'manual__2024-05-19T15:17:18.366686+00:00', '--job-id', '1973', '--raw', '--subdir', 'DAGS_FOLDER/dummyjson.py', '--cfg-path', '/tmp/tmp4qyhzp6s']
[2024-05-19T15:18:07.378+0000] {standard_task_runner.py:91} INFO - Job 1973: Subtask write_to_csv_todo
[2024-05-19T15:18:07.453+0000] {task_command.py:426} INFO - Running <TaskInstance: dummyjson.write_to_csv_todo manual__2024-05-19T15:17:18.366686+00:00 [running]> on host ca927d78a9ea
[2024-05-19T15:18:08.015+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='fathurrahmanhernanda@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dummyjson' AIRFLOW_CTX_TASK_ID='write_to_csv_todo' AIRFLOW_CTX_EXECUTION_DATE='2024-05-19T15:17:18.366686+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-19T15:17:18.366686+00:00'
[2024-05-19T15:18:08.017+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-19T15:18:08.045+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-19T15:18:08.046+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dummyjson.py", line 107, in write_to_csv_generic
    writer.writerows(transformed_data)
  File "/usr/local/lib/python3.12/csv.py", line 167, in writerows
    return self.writer.writerows(map(self._dict_to_list, rowdicts))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/csv.py", line 159, in _dict_to_list
    raise ValueError("dict contains fields not in fieldnames: "
ValueError: dict contains fields not in fieldnames: 'user_id', 'todo_id'
[2024-05-19T15:18:08.072+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dummyjson, task_id=write_to_csv_todo, run_id=manual__2024-05-19T15:17:18.366686+00:00, execution_date=20240519T151718, start_date=20240519T151807, end_date=20240519T151808
[2024-05-19T15:18:08.099+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1973 for task write_to_csv_todo (dict contains fields not in fieldnames: 'user_id', 'todo_id'; 1536)
[2024-05-19T15:18:08.154+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-19T15:18:08.212+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-19T15:18:08.217+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
